spring:
    profiles:
        active: native
    cloud:
        config:
            server:
              git:
                uri: https://github.com/GL-POC/centalized-yml-files.git
    application:
      name: central-config-server
